Repository NadyaTambunan/Multi-label_Emotion_Classification, pull requests merged in 2021-11, with the labels that each got.

#14 Import Dataset
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#15 Update Twinkle_Multi_label_Emotion_Classification.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#16 Update Twinkle_Multi_label_Emotion_Classification.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#19 Create Twinkle_Multi_label_Emotion_Classification_Compiled.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification_Compiled.ipynb
Labels: enhancement

#20 Update Twinkle_Multi_label_Emotion_Classification.ipynb
  Code/.ipynb_checkpoints/Twinkle_Multi_label_Emotion_Classification-checkpoint.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#23 Create Laporan
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: documentation

#27 Update Twinkle-LAP-PBA-GSL-21-22.docx
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: documentation

#29 Update Laporan
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: enhancement

#30 Update code
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#33 Update Twinkle-LAP-PBA-GSL-21-22.docx
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: documentation, enhancement

#41 Delete old program code
  Code/.ipynb_checkpoints/Twinkle_Multi_label_Emotion_Classification-checkpoint.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: bug, enhancement

#43 Create new code
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#45 Update Twinkle_Multi_label_Emotion_Classification.ipynb
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#46 Update Laporan dan Kode
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: enhancement

#48 Update Laporan dan Kode
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
Labels: enhancement

#49 Delete code and document
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: enhancement

#51 Update code and document
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan Akhir/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: enhancement

#53 Update document and code files
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan Akhir/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: documentation, enhancement

#55 update progress doc and code
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan Akhir/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: documentation, enhancement

#56 Update Document and Code
  Code/Twinkle_Multi_label_Emotion_Classification.ipynb
  Laporan Akhir/Twinkle-LAP-PBA-GSL-21-22.docx
Labels: enhancement
